spring:
  datasource:
    url: jdbc:postgresql://crossover.proxy.rlwy.net:26742/railway
    username: postgres
    password: DhIKTpKSlZJVHXMeVsTffwiMGTJQeeln
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true